platform :ios, '7.0'
inhibit_all_warnings!

pod 'AFNetworking', '~> 2.2'
pod 'Socialize', :podspec => 'https://raw.github.com/socialize/socialize-sdk-ios/master/Socialize.podspec'
pod 'AFSoundManager', '~> 1.1'